config/routes.rb
Airliftetest::Application.routes.draw do
  resources :hosts
  root :to => 'hosts#index'

end

app/models/host.rb
class Host < ActiveRecord::Base
  attr_accessible :flexible, :from, :time, :to, :when
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hosts }
    end
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
    @host = Host.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @host }
    end
  end

  # GET /hosts/new
  # GET /hosts/new.json
  def new
    @host = Host.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @host }
    end
  end

  # GET /hosts/1/edit
  def edit
    @host = Host.find(params[:id])
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(params[:host])

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render json: @host, status: :created, location: @host }
      else
        format.html { render action: "new" }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hosts/1
  # PUT /hosts/1.json
  def update
    @host = Host.find(params[:id])

    respond_to do |format|
      if @host.update_attributes(params[:host])
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host = Host.find(params[:id])
    @host.destroy

    respond_to do |format|
      format.html { redirect_to hosts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from, :class => 'address-picker-input'  %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :to, :class => 'address-picker-input'  %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
    <%= f.date_select :when %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :flexible %><br />
    <%= f.check_box :flexible %>
  </div>
  
  <!-- ============================================================================ -->

    <script type="text/javascript">

        //AddressPickerRails.Pickers.applyOnReady({
        //    'onLoad':function (railsPicker) {
        //        console.debug("callback for a single pond with ID '%s'", railsPicker.getIdPrefix());
        //    }
        //});

        AddressPickerRails.Pickers.apply({
            'onLoad':function (railsPicker) {
                console.debug("callback for a single host with ID '%s'", railsPicker.getIdPrefix());
            }
        });
    </script>

    <!-- ============================================================================ -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<h1>Listing hosts</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>When</th>
    <th>Time</th>
    <th>Flexible</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hosts.each do |host| %>
  <tr>
    <td><%= host.from %></td>
    <td><%= host.to %></td>
    <td><%= host.when %></td>
    <td><%= host.time %></td>
    <td><%= host.flexible %></td>
    <td><%= link_to 'Show', host %></td>
    <td><%= link_to 'Edit', edit_host_path(host) %></td>
    <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @host.from %>
</p>

<p>
  <b>To:</b>
  <%= @host.to %>
</p>

<p>
  <b>When:</b>
  <%= @host.when %>
</p>

<p>
  <b>Time:</b>
  <%= @host.time %>
</p>

<p>
  <b>Flexible:</b>
  <%= @host.flexible %>
</p>


<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airliftetest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>